# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ${file(./local.yml):organisation}
# "service" is the name of this project. This will also be added to your AWS resource names.
service: bionicBackend
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentMethod: direct
  iam:
    role: ${file(./local.yml):iamRole}
  httpApi:
    cors: true 

build:
  esbuild:
    minify: true

package:
  individually: true

functions:
  CreateMenuD:
    handler: src/functions/CreateMenuDb/index.handler
    events:
      - httpApi:
          path: /api/create-menu
          method: post


  AddOrderToDb:
    handler: src/functions/AddOrderToDb/index.handler
    events:
      - httpApi:
          path: /api/create-order
          method: post
  
  GetMenu:
    handler: src/functions/GetMenu/index.handler
    events:
      - httpApi:
          path: /api/get-menu
          method: get


  SortMenu:
    handler: src/functions/SortMenu/index.handler
    events:
      - httpApi:
          path: /api/sort-menu
          method: post       

  AddUser:
    handler: src/functions/AddUser/index.handler
    events:
      - httpApi:
          path: /api/add-user
          method: post

resources:
  Resources:
    TestMenuTable: # Första tabellen (menu-db)
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "menus-to-db" # Namnet på din tabell
        AttributeDefinitions:
          - AttributeName: "MenuItemID" # Definiera attribut för din partition key
            AttributeType: "S" # S för sträng
           
        KeySchema:
          - AttributeName: "MenuItemID" # Partition key
            KeyType: HASH # Detta är din PK (Partition Key)
        BillingMode: PAY_PER_REQUEST # Betalning per användning       

    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "user-to-db"
        AttributeDefinitions:
          - AttributeName: "userid"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "userid"
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    
    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "orders-db"
        AttributeDefinitions:
          - AttributeName: "orderItemID"
            AttributeType: "S"
          - AttributeName: "customerID" # Definiera attribut för din sort key (om du vill ha en)
            AttributeType: "S" # S för sträng
        KeySchema:
          - AttributeName: "orderItemID"
            KeyType: HASH
          - AttributeName: "customerID"
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST