# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ${file(./local.yml):organisation}
# "service" is the name of this project. This will also be added to your AWS resource names.
service: bionicBackend
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentMethod: direct
  iam:
    role: ${file(./local.yml):iamRole}

build:
  esbuild:
    minify: true

package:
  individually: true

functions:
  CreateMenuD:
    handler: src/functions/CreateMenuDb/index.handler
    events:
      - httpApi:
          path: /api/create-menu
          method: post

resources:
  Resources:
    TestMenuTable: # Första tabellen (menu-db)
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "menu-db" # Namnet på din tabell
        AttributeDefinitions:
          - AttributeName: "MenuItemID" # Definiera attribut för din partition key
            AttributeType: "S" # S för sträng
           
        KeySchema:
          - AttributeName: "MenuItemID" # Partition key
            KeyType: HASH # Detta är din PK (Partition Key)
        BillingMode: PAY_PER_REQUEST # Betalning per användning       

    